name: PlutonEXP
version: '1.16'
main: net.plutondev.expShop.ExpShop
api-version: '1.20'

commands:
  expshop:
    description: Opens the experience shop menu
    aliases: [plutonexp, xpshop, xpmenu, expmenu, eshop]